src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\Table(name="order_product")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $productId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cityRef;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postOfficeRef;

    /**
     * @ORM\ManyToOne(targetEntity="Product")
     */
    private $product;

    /**
     * @ORM\OneToMany(targetEntity="OrderPayment", mappedBy="order")
     */
    private $payments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $addName;

    public function __construct()
    {
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->productId;
    }

    public function setProductId(?int $productId): self
    {
        $this->productId = $productId;

        return $this;
    }

    public function getCityRef(): ?string
    {
        return $this->cityRef;
    }

    public function setCityRef(?string $cityRef): self
    {
        $this->cityRef = $cityRef;

        return $this;
    }

    public function getPostOfficeRef(): ?string
    {
        return $this->postOfficeRef;
    }

    public function setPostOfficeRef(?string $postOfficeRef): self
    {
        $this->postOfficeRef = $postOfficeRef;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    /**
     * @return Collection|OrderPayment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(OrderPayment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setOrder($this);
        }

        return $this;
    }

    public function removePayment(OrderPayment $payment): self
    {
        if ($this->payments->contains($payment)) {
            $this->payments->removeElement($payment);
            // set the owning side to null (unless already changed)
            if ($payment->getOrder() === $this) {
                $payment->setOrder(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return float
     */
    public function getAmount(): float
    {
        return $this->getProductAmount() + $this->getDeliveryAmount();
    }

    /**
     * @return float
     */
    public function getProductAmount(): float
    {
        return $this->product ? (float)$this->getProduct()->getPrice() : 0;
    }

    /**
     * @return float
     */
    public function getDeliveryAmount(): float
    {
        return 50;
    }

    /**
     * @return float
     */
    public function getPaymentAmount(): float
    {
        $result = 0;
        foreach ($this->getPayments() as $payment){
            $result += $payment->getAmount();
        }
        return $result;
    }

    /**
     * @return bool
     */
    public function isPaid(): bool
    {
        if (null === $this->getProduct()){
            return false;
        }
        return $this->getPaymentAmount() >= $this->getAmount();
    }

    public function getAddName(): ?string
    {
        return $this->addName;
    }

    public function setAddName(?string $addName): self
    {
        $this->addName = $addName;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{

    const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="array")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @param string $role
     * @return $this
     */
    public function addRole(string  $role): self
    {
        $this->roles[] = $role;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no">
    <title>{% block title %}Olx{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="/css/swiper.min.css">
        <link rel="stylesheet" href="/style.css">
        <link rel="icon" href="/favicon.ico">
    {% endblock %}
</head>
<body>
{% block header %}
<header class="header">
    <div class="header-fx">
        <div class="header-btn__logo">
            <a href="#" class="button-back">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14" color="#fff"
                     style="height: 14px; width: 14px;">
                    <path fill="currentColor" d="M14 6.125H3.351l4.891-4.891L7 0 0 7l7 7 1.234-1.234L3.35 7.875H14z"
                          fill-rule="evenodd"></path>
                </svg>
            </a>
            <a href="https://www.olx.ua/" class="olx-logo has-backButtonTransition"></a>
        </div>


        <ul class="header-nav">
            <li class="header-nav_item">
                <a href="https://www.olx.ua/ru/i2/adding" class="header-nav_link">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17 17" color="#fff"
                         style="height: 20px; width: 20px;">
                        <path fill="currentColor"
                              d="M16.958 9.708h-7.25v7.25H7.292v-7.25H.042V7.292h7.25V.042h2.416v7.25h7.25z"
                              fill-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
            <li class="header-nav_item">
                <a href="https://m.olx.ua/account/menu/" class="header-nav_link">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" color="#fff"
                         style="height: 20px; width: 20px;">
                        <g fill="currentColor" fill-rule="evenodd">
                            <circle cx="9" cy="4.5" r="4.5"></circle>
                            <path d="M9 11.25c-3.004 0-9 1.508-9 4.5V18h18v-2.25c0-2.992-5.996-4.5-9-4.5z"></path>
                        </g>
                    </svg>
                </a>
            </li>
            <li class="header-nav_item relative-item item__height">
                <a href="https://m.olx.ua/myaccount/answers/" class="header-nav_link relative-item">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" color="#fff"
                         class="c-navigation__messages-icon" style="height: 20px; width: 20px;">
                        <path fill="currentColor"
                              d="M18 0H2C.9 0 .01.9.01 2L0 14c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V2l8 5 8-5v2z"
                              fill-rule="evenodd"></path>
                    </svg>
                    <div class="mess-counter"></div>
                </a>
            </li>
            <li class="header-nav_item ">
                <a href="https://m.olx.ua/favorites/" class="header-nav_link ">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 19" color="#fff"
                         style="height: 20px; width: 20px;">
                        <path fill="currentColor"
                              d="M16.18 19l-1.635-7.029L20 7.244l-7.191-.617L10 0 7.191 6.627 0 7.244l5.455 4.727L3.82 19 10 15.272z"></path>
                    </svg>
                </a>
            </li>
            <li class="header-nav_item">
                <a href="https://m.olx.ua/searchform/" class="header-nav_link">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 21" color="#fff"
                         style="height: 20px; width: 20px;">
                        <g fill="#FFF" fill-rule="evenodd">
                            <path d="M20 4.5v-2H0v2z"></path>
                            <circle cx="5" cy="3.5" r="3"></circle>
                            <g transform="translate(0 7)">
                                <path d="M20 4.5v-2H0v2z"></path>
                                <circle cx="14" cy="3.5" r="3"></circle>
                            </g>
                            <g transform="translate(0 14)">
                                <path d="M20 4.5v-2H0v2z"></path>
                                <circle cx="8" cy="3.5" r="3"></circle>
                            </g>
                        </g>
                    </svg>
                </a>
            </li>
        </ul>
    </div>
</header>
{% endblock %}
{% block body %}

{% endblock %}


{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="/js/swiper.min.js"></script>
    <script src="/script.js"></script>
{% endblock %}
</body>
</html>

templates/base_order.html.twig
<!DOCTYPE html>
<!-- saved from url=(0060)https://olx.ua.obyavlenie.co/safedeal/payment/633659717/pay/ -->
<html style="/*! --vh:8.12px; */" class="">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no">
    <meta name="theme-color" content="#f9f9f9">
    <meta name="version" content="eecf12428_ade29">

    <title>Сервис объявлений OLX: сайт частных объявлений в Украине - купля/продажа б/у товаров на OLX.ua</title>
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="robots" content="noindex, nofollow" data-react-helmet="true">
    <meta name="description"
          content="OLX.ua - крупнейший сервис объявлений Украины. Огромная база предложений по темам: недвижимость, работа, транспорт, купля/продажа товаров, услуги и многое другое на OLX.ua!"
          data-react-helmet="true">

    {% block css %}

        <link rel="stylesheet" href="/original/normalize.min.css">
        <link rel="manifest" href="https://m.olx.ua/manifest.json">
        <link rel="shortcut icon" href="https://m.olx.ua/favicon.ico">
        <link rel="stylesheet" href="/original/style.css" type="text/css" media="all">
        <link href="/original/font-awesome.css" rel="stylesheet">
        <link rel="apple-touch-startup-image"
              media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
              href="https://static-olxeu.akamaized.net/app/splash_1125_2436.png">
        <link rel="apple-touch-startup-image"
              media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
              href="https://static-olxeu.akamaized.net/app/splash_750_1334.png">
        <link rel="apple-touch-startup-image"
              media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)"
              href="https://static-olxeu.akamaized.net/app/splash_1242_2208.png">
        <link rel="apple-touch-startup-image"
              media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
              href="https://static-olxeu.akamaized.net/app/splash_640_1136.png">
        <link rel="apple-touch-startup-image"
              media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
              href="https://static-olxeu.akamaized.net/app/splash_1536_2048.png">
        <link rel="apple-touch-startup-image"
              media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
              href="https://static-olxeu.akamaized.net/app/splash_1668_2224.png">
        <link rel="apple-touch-startup-image"
              media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
              href="https://static-olxeu.akamaized.net/app/splash_2048_2732.png">
        <link rel="apple-touch-icon" href="https://static-olxeu.akamaized.net/app/apple-touch-icon.png">
        <link href="/original/css.css" rel="stylesheet">
{#        <link href="./info_files/css" rel="stylesheet">#}
    {% endblock %}

</head>
<body class="">
<div id="didomi-host"></div>
<iframe name="__cmpLocator" style="display: none;" src="/original/saved_resource.html"></iframe>
<div id="root">
    <div class="t-mobile">
        {% block body %}
        {% endblock %}
    </div>
    <div></div>
    <div id="modalRoot"></div>
</div>
<noscript>This page needs javascript to run.</noscript>

</div>
</div>

{% block js %}
<script src="/original/jquery.min.js"></script>
{% endblock %}
</body>
</html>

templates/login.html.twig
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css') }}">

</head>
<body>
<main>
    <div class="container">
        <form method="post">


            {% if app.user %}
                <div class="mb-3">
                    You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
                </div>
            {% endif %}


            <h1 class="h3 mb-3 font-weight-normal">Введите логин и пароль</h1>
            {% if error %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}
            <div class="form-group">
                <label for="inputEmail">Email</label>
                <input type="text" value="{{ last_username }}" name="email" id="inputEmail" class="form-control"
                       required autofocus>
            </div>
            <div class="form-group">
                <label for="inputPassword">Пароль</label>
                <input type="password" name="password" id="inputPassword" class="form-control" required>
            </div>


            <input type="hidden" name="_csrf_token"
                   value="{{ csrf_token('authenticate') }}"
            >
            <div class="form-group">
                <button class="btn btn-lg btn-primary" type="submit">
                    Войти
                </button>
            </div>
        </form>
    </div>
</main>
</body>
</html>

templates/order.address.html.twig
{% extends 'base_order.html.twig' %}

{% block body %}
<div class="c-layout">
    <form class="c-filters-component" novalidate="">
        {% include 'partial/olx-header.html.twig' with {'href': path('order.info', {'id': order.product.id}), 'title' : 'Выбор города'} %}

        <div class="c-query-field">
            <div class="c-query-field__background"></div>
            <div class="c-query-field__input-container">
                <input id="search-city-name" type="text" name="query" class="c-query-field__input" placeholder="Поиск" autocomplete="off" tabindex="-1" data-cy="search-input" value="">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19 19" color="#0198D0" class="c-query-field__icon" style="height: 17px; width: 17px;">
                    <path fill="currentColor" d="M12.451 11.75l-.277-.268a6.397 6.397 0 001.552-4.181 6.425 6.425 0 10-6.425 6.425 6.397 6.397 0 004.181-1.552l.267.277v.781l4.943 4.933 1.473-1.473-4.933-4.943h-.78zm-9.66-4.408a4.544 4.544 0 014.55-4.55 4.544 4.544 0 014.55 4.55 4.544 4.544 0 01-4.55 4.55 4.544 4.544 0 01-4.55-4.55z" fill-rule="evenodd"></path>
                </svg>
            </div>
            <div class="c-query-suggestions"></div>
        </div>
        <div class="ripple-button filter-selector" title="Выберите рубрику" style="overflow: hidden;margin: 1px 0;">
            <div class="filter-selector__label" id="search-result">
            </div>
            <div class="c-footer">
            </div>
        </div>

    </form>
    <div></div>
    <div id="modalRoot"></div>
</div>





        {{ form_start(form, {'attr': {'id' : 'post-office-form'}}) }}


        {{ form_widget(form.postOfficeRef, {'attr': {'id' : 'post-office-input'}}) }}


        {{ form_end(form) }}


{% endblock %}

{% block js %}
{{ parent() }}
    {{ encore_entry_script_tags('order_address') }}
{% endblock %}

templates/order.info.html.twig
{% extends 'base_order.html.twig' %}

{% block body %}



    <div class="c-layout">
        <form class="c-filters-component" novalidate="" method="post" id="form-user-info">

            {% include 'partial/olx-header.html.twig' with {'href': path('products', {'alias': pr.alias}), 'title': 'Данные доставки'} %}

            <div class="ripple-button filter-selector" style="overflow: hidden;">
                <div class="wowmathoer">
                    <img src="{{ pr.img }}" height="58px" style="max-height: 58px;">
                </div>
                <div class="filter-selector__label">
                    <h4 class="c-single-select__title2">Продавец: {{ pr.author }}</h4>
                    <h4 class="c-single-select__title3">{{ pr.name }}</h4>
                    <h4 class="c-single-select__title4">{{ pr.price }} грн.</h4>
                </div>
            </div>
            <div class="titlenadnad">Контактные данные:</div>

            <div class="c-price-field__item">
                <div class="c-single-select__title5">Фамилия</div>
                <div class="c-range-price">
                    <div class="c-range-price__col">
                        {{ form_widget(form.lastName, {'attr': {'class': 'c-range-price__textField'}}) }}
                    </div>
                </div>
            </div>
            <div class="c-price-field__item">
                <div class="c-single-select__title5">Имя</div>
                <div class="c-range-price">
                    <div class="c-range-price__col">
                        {{ form_widget(form.firstName, {'attr': {'class': 'c-range-price__textField'}}) }}
                    </div>
                </div>
            </div>
            <div class="c-price-field__item">
                <div class="c-single-select__title5">Отчество</div>
                <div class="c-range-price">
                    <div class="c-range-price__col">
                        {{ form_widget(form.addName, {'attr': {'class': 'c-range-price__textField'}}) }}
                    </div>
                </div>
            </div>
            <div class="c-price-field__item">
                <div class="c-single-select__title5">Телефон</div>
                <div class="c-range-price">
                    <div class="c-range-price__col">
                        {{ form_widget(form.phone, {'attr': {'class': 'c-range-price__textField'}}) }}
                    </div>
                </div>
            </div>
            <div class="c-price-field__item">
                <div class="c-single-select__title5">E-mail</div>
                <div class="c-range-price">
                    <div class="c-range-price__col">
                        {{ form_widget(form.email, {'attr': {'class': 'c-range-price__textField'}}) }}
                        <div style="color: red">{{ form_errors(form.email) }}</div>
                    </div>
                </div>
            </div>
            <div>

            </div>

            <div class="c-filters-component__footer">
                <div class="ripple-button" style="overflow: hidden;width: 97%;">
                    <a onclick="document.getElementById('form-user-info').submit();"
                       class="btn-component btn-search-form qa-btn-search-form"><span>Выбрать отделение "Нова пошта"</span>
                    </a>
                </div>
            </div>
        </form>
        <div class="c-footer">
        </div>
    </div>


    {#        <div class="row">#}

    {#            <div class="col-3">#}
    {#                <img src="{{ pr.img }}" width="100%">#}
    {#            </div>#}
    {#            <div class="col-9">#}
    {#                <p style="margin-bottom: 0">Продавец: {{ pr.author }}</p>#}
    {#                <p style="margin-bottom: 0" class="font-weight-bold">{{ pr.name }}</p>#}
    {#                <p style="margin-bottom: 0">{{ pr.price }} грн.</p>#}
    {#            </div>#}

    {#        </div>#}

    {#        <div style="margin-top: 10px">#}
    {#            <p class="text-center  ">Контактная информация</p>#}
    {#            {{ form_start(form) }}#}
    {#            <div class="form-group">#}
    {#                <label class="mr-sm-2">Фамилия</label>#}
    {#                {{ form_widget(form.lastName, {'attr': {'class': 'form-control'}}) }}#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <label class="mr-sm-2">Имя</label>#}
    {#                {{ form_widget(form.firstName, {'attr': {'class': 'form-control'}}) }}#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <label class="mr-sm-2">Телефон</label>#}
    {#                {{ form_widget(form.phone, {'attr': {'class': 'form-control'}}) }}#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <label class="mr-sm-2">Email</label>#}
    {#                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <button class="btn btn-primary form-control">Далее</button>#}
    {#            </div>#}

    {#            {{ form_end(form) }}#}
    {#        </div>#}



{% endblock %}

templates/order.payment.html.twig
{% extends 'base_order.html.twig' %}
{% block body %}
    <form id="form-payment" class="c-filters-component" novalidate="" method="post"
          action="https://wl.walletone.com/checkout/checkout/Index">


        {% include 'partial/olx-header.html.twig' with {'href': path('order.address'), 'title': 'Оформление доставки'} %}

        <div class="titlenadnad2"><img src="/original/lock1.png" style="max-height: 20px;margin-bottom: 3px;"
                                       height="20px"> Укажите карту для оплаты
        </div>
        <div class="ripple-button text-wow"
             style="overflow: hidden;width: 97%;background:#fffbf2;border-radius: 5px;border: 1px solid #e5e6c2;margin-left: 6px;">
            <div style="margin-left:5px;margin-top:10px;"><img src="/original/i.png"
                                                               style="max-height: 14px;margin-bottom: 3px;margin-right:5px;"
                                                               height="14px">Как происходит оплата?
                <br>
            </div>
            <div style="margin-left:20px;margin-top:15px;margin-right:15px;margin-bottom:10px;">
                <h4 class="c-single-select__title3" style="font-size:12.5px;">
                    Деньги зачислятся на карту продавца только после того, как вы
                    проверите товар в отделении Нова Пошта. Деньги вернутся на вашу карту,
                    если товар не подошел. По вопросам, связанным с оплатой,
                    обращайтесь по номеру <span style="color:#0198d0;">0800208888</span></h4>
            </div>
        </div>


        <div class="titlenadnad2" style="font-weight: 599;">Итого:</div>

        <div class="c-price-field__item2">
            <div class="c-single-select__title5">Стоимость товара<span
                    style="font-weight:599;float:right;color:#000;">{{ order.productAmount }} грн.</span></div>
            <div class="c-range-price">
            </div>
        </div>
        <div class="c-price-field__item2">
            <div class="c-single-select__title5">Стоимость доставки<span
                    style="font-weight:599;float:right;color:#000;">{{ order.deliveryAmount }} грн.</span></div>
            <div class="c-range-price">
            </div>
        </div>
        <div class="c-price-field__item2">
            <div class="c-single-select__title5" style="color:#f4960f;">Без комиссии за перевод<span
                    style="font-weight:500;float:right;color:#000;">0.00 грн.</span></div>
            <div class="c-single-select__title5" style="margin-top:30px;">К оплате<span
                    style="font-weight:599;float:right;color:#000;font-size:17px;">{{ order.amount }} грн.</span></div>
            <div class="c-range-price">
            </div>
        </div>
        <div class="titlenadna5" style="font-weight: 400">Платежi захищенi:</div>
        <div class="titlenadna7" style="display: flex;align-items: center;justify-content: space-between;">
            <div class="visa"
                 style="background-image: url(https://olx.uapay.ua/delivery/6208eb893410762f9d7b7a66fdc44deb.svg);/*! width: 40px; *//*! height: 40px; */background-repeat: no-repeat;width: 62px;height: 29px;/*! display: flex; */">
            </div>
            <div class="mc"
                 style="background-image: url(https://olx.uapay.ua/delivery/2285939b236807abd4af869829674373.svg);width: 62px;height: 23px;background-repeat: no-repeat;">
            </div>
            <div class="uapay"
                 style="width: 62px;height: 26px;background-image: url(https://olx.uapay.ua/delivery/a06e5430f40d0cde347d18c76d72c7f7.svg);/*! color: #8e8e8e; */background-repeat: no-repeat;">

            </div>
        </div>
        <style>
            .ic {
                width: 14px;
                height: 6px;
            }
        </style>

        <div class="ripple-button text-wow"
             style="overflow: hidden;width: 97%;background:#fffbf2;border-radius: 5px;border: 1px solid #e5e6c2;margin-left: 6px;margin-top:10px;">
            <div style="margin-left:5px;margin-top:10px;"><img src="/original/i.png"
                                                               style="max-height: 14px;margin-bottom: 3px;margin-right:5px;"
                                                               height="14px">Правовая информация
                <br>
            </div>
            <div style="margin-left:20px;margin-top:15px;margin-right:15px;margin-bottom:10px;">
                <h4 class="c-single-select__title3" style="font-size: 12px;">
                    Нажимая кнопку "Оплатить", вы соглашаетесь с <span style="text-decoration: underline;">
 условиями публичных договоров, условиями соглашения на обработку своих
персональных данных, условиями
							предоставления услуг логистическим партнёром, публичным договором
 о предоставлении услуг по организации перевозки отправлений, </span> а также принимаете <span
                        style="text-decoration: underline;">Правила предоставления сервиса \"OLX Доставка\".</span></h4>
            </div>
        </div>

        <div style="height:30px;"></div>

        <div class="c-filters-component__footer">
            <div class="ripple-button" style="overflow: hidden;width: 97%;">
                <a onclick="document.getElementById('form-payment').submit();"
                   class="btn-component btn-search-form qa-btn-search-form" id="btn_sumbit" style="background:#49b3da;"><span>Оплатить {{ order.amount }} грн.<img
                            src="/original/lock.png"
                            style="max-height: 20px;margin-bottom: 3px;z-index:1023123123;margin-left:5px;"
                            height="20px"></span>
                </a>
            </div>
        </div>
                  <input type="hidden" name="WMI_MERCHANT_ID"     value="{{ merchantID }}"/>
                  <input type="hidden" name="WMI_PAYMENT_AMOUNT" value="{{ order.amount }}"/>
                  <input type="hidden" name="WMI_CURRENCY_ID"    value="980"/>
                  <input type="hidden" name="WMI_SUCCESS_URL" value="{{ absolute_url(path('order.payment_result_success')) }}"/>
                  <input type="hidden" name="WMI_FAIL_URL" value="{{ absolute_url(path('order.payment_result_error')) }}"/>
    </form>
{% endblock %}